[package]
name = "coddog"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4.16", features = ["derive"] }
colored = "2.1.0"
config = { version = "0.13.4", features = ["toml"] }
glob = "0.3.1"
mapfile_parser = "2.3.1"
rabbitizer = "1.8.1"
triple_accel = "0.4.0"
