[package]
name = "coddog"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.12", features = ["derive"] }
config = { version = "0.13.4", features = ["toml"] }
glob = "0.3.1"
mapfile_parser = "2.3.1"
rabbitizer = "1.8.1"
