[package]
name = "coddog"
version = "0.4.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.17", features = ["derive"] }
colored = "2.1.0"
decomp_settings = "0.0.7"
editdistancek = "1.0.2"
glob = "0.3.1"
mapfile_parser = "2.6.0"
object = "0.36.4"