[package]
name = "coddog-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../README.md"
description = """
A library for finding matching sequences of code among binaries
"""

[dependencies]
anyhow = "1.0"
editdistancek = "1.0.2"
object = "0.37.1"
mapfile_parser = "2.9.4"
ppc750cl = "0.3.3"
rabbitizer = { version = "2.0.0-alpha.3", features = ["all_extensions"] }